[2024-12-02T08:09:26.221+0000] {processor.py:161} INFO - Started process (PID=47) to work on /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:09:26.221+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_cleanning.py for tasks to queue
[2024-12-02T08:09:26.223+0000] {logging_mixin.py:188} INFO - [2024-12-02T08:09:26.223+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:09:26.942+0000] {logging_mixin.py:188} INFO - [2024-12-02T08:09:26.937+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/data_cleanning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_cleanning.py", line 5, in <module>
    from data_cleaning import clean_data
ModuleNotFoundError: No module named 'data_cleaning'
[2024-12-02T08:09:26.943+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:09:26.973+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_cleanning.py took 0.754 seconds
[2024-12-02T08:09:57.675+0000] {processor.py:161} INFO - Started process (PID=62) to work on /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:09:57.676+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_cleanning.py for tasks to queue
[2024-12-02T08:09:57.678+0000] {logging_mixin.py:188} INFO - [2024-12-02T08:09:57.677+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:09:58.052+0000] {logging_mixin.py:188} INFO - [2024-12-02T08:09:58.048+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/data_cleanning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_cleanning.py", line 5, in <module>
    from data_cleaning import clean_data
ModuleNotFoundError: No module named 'data_cleaning'
[2024-12-02T08:09:58.053+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:09:58.067+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_cleanning.py took 0.396 seconds
[2024-12-02T08:10:28.872+0000] {processor.py:161} INFO - Started process (PID=77) to work on /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:10:28.873+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_cleanning.py for tasks to queue
[2024-12-02T08:10:28.875+0000] {logging_mixin.py:188} INFO - [2024-12-02T08:10:28.875+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:10:29.267+0000] {logging_mixin.py:188} INFO - [2024-12-02T08:10:29.262+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/data_cleanning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_cleanning.py", line 5, in <module>
    from data_cleaning import clean_data
ModuleNotFoundError: No module named 'data_cleaning'
[2024-12-02T08:10:29.268+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:10:29.287+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_cleanning.py took 0.418 seconds
[2024-12-02T08:11:00.241+0000] {processor.py:161} INFO - Started process (PID=92) to work on /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:11:00.242+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_cleanning.py for tasks to queue
[2024-12-02T08:11:00.245+0000] {logging_mixin.py:188} INFO - [2024-12-02T08:11:00.244+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:11:00.697+0000] {logging_mixin.py:188} INFO - [2024-12-02T08:11:00.694+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/data_cleanning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_cleanning.py", line 5, in <module>
    from data_cleaning import clean_data
ModuleNotFoundError: No module named 'data_cleaning'
[2024-12-02T08:11:00.698+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:11:00.721+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_cleanning.py took 0.483 seconds
[2024-12-02T08:11:31.145+0000] {processor.py:161} INFO - Started process (PID=107) to work on /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:11:31.146+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_cleanning.py for tasks to queue
[2024-12-02T08:11:31.149+0000] {logging_mixin.py:188} INFO - [2024-12-02T08:11:31.149+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:11:31.585+0000] {logging_mixin.py:188} INFO - [2024-12-02T08:11:31.581+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/data_cleanning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_cleanning.py", line 5, in <module>
    from data_cleaning import clean_data
ModuleNotFoundError: No module named 'data_cleaning'
[2024-12-02T08:11:31.587+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:11:31.608+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_cleanning.py took 0.466 seconds
[2024-12-02T08:12:01.674+0000] {processor.py:161} INFO - Started process (PID=122) to work on /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:12:01.675+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_cleanning.py for tasks to queue
[2024-12-02T08:12:01.678+0000] {logging_mixin.py:188} INFO - [2024-12-02T08:12:01.677+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:12:02.147+0000] {logging_mixin.py:188} INFO - [2024-12-02T08:12:02.143+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/data_cleanning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_cleanning.py", line 5, in <module>
    from data_cleaning import clean_data
ModuleNotFoundError: No module named 'data_cleaning'
[2024-12-02T08:12:02.150+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:12:02.169+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_cleanning.py took 0.499 seconds
[2024-12-02T08:12:32.990+0000] {processor.py:161} INFO - Started process (PID=137) to work on /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:12:32.991+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_cleanning.py for tasks to queue
[2024-12-02T08:12:32.993+0000] {logging_mixin.py:188} INFO - [2024-12-02T08:12:32.992+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:12:33.400+0000] {logging_mixin.py:188} INFO - [2024-12-02T08:12:33.396+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/data_cleanning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_cleanning.py", line 5, in <module>
    from data_cleaning import clean_data
ModuleNotFoundError: No module named 'data_cleaning'
[2024-12-02T08:12:33.401+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:12:33.419+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_cleanning.py took 0.431 seconds
[2024-12-02T08:13:04.172+0000] {processor.py:161} INFO - Started process (PID=152) to work on /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:13:04.172+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_cleanning.py for tasks to queue
[2024-12-02T08:13:04.174+0000] {logging_mixin.py:188} INFO - [2024-12-02T08:13:04.174+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:13:04.522+0000] {logging_mixin.py:188} INFO - [2024-12-02T08:13:04.519+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/data_cleanning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_cleanning.py", line 5, in <module>
    from data_cleaning import clean_data
ModuleNotFoundError: No module named 'data_cleaning'
[2024-12-02T08:13:04.523+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:13:04.537+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_cleanning.py took 0.368 seconds
[2024-12-02T08:13:35.300+0000] {processor.py:161} INFO - Started process (PID=167) to work on /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:13:35.301+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_cleanning.py for tasks to queue
[2024-12-02T08:13:35.303+0000] {logging_mixin.py:188} INFO - [2024-12-02T08:13:35.303+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:13:35.674+0000] {logging_mixin.py:188} INFO - [2024-12-02T08:13:35.670+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/data_cleanning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_cleanning.py", line 5, in <module>
    from data_cleaning import clean_data
ModuleNotFoundError: No module named 'data_cleaning'
[2024-12-02T08:13:35.675+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:13:35.691+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_cleanning.py took 0.394 seconds
[2024-12-02T08:14:06.495+0000] {processor.py:161} INFO - Started process (PID=182) to work on /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:14:06.495+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_cleanning.py for tasks to queue
[2024-12-02T08:14:06.498+0000] {logging_mixin.py:188} INFO - [2024-12-02T08:14:06.497+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:14:06.867+0000] {logging_mixin.py:188} INFO - [2024-12-02T08:14:06.863+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/data_cleanning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_cleanning.py", line 5, in <module>
    from data_cleaning import clean_data
ModuleNotFoundError: No module named 'data_cleaning'
[2024-12-02T08:14:06.868+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:14:06.883+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_cleanning.py took 0.391 seconds
[2024-12-02T08:14:37.938+0000] {processor.py:161} INFO - Started process (PID=198) to work on /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:14:37.939+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_cleanning.py for tasks to queue
[2024-12-02T08:14:37.942+0000] {logging_mixin.py:188} INFO - [2024-12-02T08:14:37.941+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:14:38.331+0000] {logging_mixin.py:188} INFO - [2024-12-02T08:14:38.327+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/data_cleanning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_cleanning.py", line 5, in <module>
    from data_cleaning import clean_data
ModuleNotFoundError: No module named 'data_cleaning'
[2024-12-02T08:14:38.332+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:14:38.347+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_cleanning.py took 0.412 seconds
[2024-12-02T08:15:08.761+0000] {processor.py:161} INFO - Started process (PID=214) to work on /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:15:08.762+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_cleanning.py for tasks to queue
[2024-12-02T08:15:08.765+0000] {logging_mixin.py:188} INFO - [2024-12-02T08:15:08.764+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:15:09.130+0000] {logging_mixin.py:188} INFO - [2024-12-02T08:15:09.127+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/data_cleanning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_cleanning.py", line 5, in <module>
    from data_cleaning import clean_data
ModuleNotFoundError: No module named 'data_cleaning'
[2024-12-02T08:15:09.131+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:15:09.146+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_cleanning.py took 0.388 seconds
[2024-12-02T08:15:42.103+0000] {processor.py:161} INFO - Started process (PID=229) to work on /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:15:42.104+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_cleanning.py for tasks to queue
[2024-12-02T08:15:42.108+0000] {logging_mixin.py:188} INFO - [2024-12-02T08:15:42.108+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:15:42.652+0000] {logging_mixin.py:188} INFO - [2024-12-02T08:15:42.648+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/data_cleanning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_cleanning.py", line 5, in <module>
    from data_cleaning import clean_data
ModuleNotFoundError: No module named 'data_cleaning'
[2024-12-02T08:15:42.655+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:15:42.677+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_cleanning.py took 0.579 seconds
[2024-12-02T08:16:13.372+0000] {processor.py:161} INFO - Started process (PID=250) to work on /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:16:13.373+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_cleanning.py for tasks to queue
[2024-12-02T08:16:13.375+0000] {logging_mixin.py:188} INFO - [2024-12-02T08:16:13.375+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:16:13.785+0000] {logging_mixin.py:188} INFO - [2024-12-02T08:16:13.781+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/data_cleanning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_cleanning.py", line 5, in <module>
    from data_cleaning import clean_data
ModuleNotFoundError: No module named 'data_cleaning'
[2024-12-02T08:16:13.786+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:16:13.803+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_cleanning.py took 0.434 seconds
[2024-12-02T08:16:44.500+0000] {processor.py:161} INFO - Started process (PID=265) to work on /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:16:44.501+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_cleanning.py for tasks to queue
[2024-12-02T08:16:44.503+0000] {logging_mixin.py:188} INFO - [2024-12-02T08:16:44.503+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:16:44.899+0000] {logging_mixin.py:188} INFO - [2024-12-02T08:16:44.895+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/data_cleanning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_cleanning.py", line 5, in <module>
    from data_cleaning import clean_data
ModuleNotFoundError: No module named 'data_cleaning'
[2024-12-02T08:16:44.901+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:16:44.917+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_cleanning.py took 0.420 seconds
[2024-12-02T08:17:15.716+0000] {processor.py:161} INFO - Started process (PID=280) to work on /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:17:15.717+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_cleanning.py for tasks to queue
[2024-12-02T08:17:15.719+0000] {logging_mixin.py:188} INFO - [2024-12-02T08:17:15.719+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:17:16.065+0000] {logging_mixin.py:188} INFO - [2024-12-02T08:17:16.062+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/data_cleanning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_cleanning.py", line 5, in <module>
    from data_cleaning import clean_data
ModuleNotFoundError: No module named 'data_cleaning'
[2024-12-02T08:17:16.066+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:17:16.079+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_cleanning.py took 0.366 seconds
[2024-12-02T08:17:46.536+0000] {processor.py:161} INFO - Started process (PID=295) to work on /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:17:46.537+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_cleanning.py for tasks to queue
[2024-12-02T08:17:46.539+0000] {logging_mixin.py:188} INFO - [2024-12-02T08:17:46.539+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:17:47.048+0000] {logging_mixin.py:188} INFO - [2024-12-02T08:17:47.045+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/data_cleanning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_cleanning.py", line 5, in <module>
    from data_cleaning import clean_data
ModuleNotFoundError: No module named 'data_cleaning'
[2024-12-02T08:17:47.049+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:17:47.067+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_cleanning.py took 0.534 seconds
[2024-12-02T08:18:17.687+0000] {processor.py:161} INFO - Started process (PID=312) to work on /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:18:17.688+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_cleanning.py for tasks to queue
[2024-12-02T08:18:17.690+0000] {logging_mixin.py:188} INFO - [2024-12-02T08:18:17.689+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:18:18.074+0000] {logging_mixin.py:188} INFO - [2024-12-02T08:18:18.071+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/data_cleanning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_cleanning.py", line 5, in <module>
    from data_cleaning import clean_data
ModuleNotFoundError: No module named 'data_cleaning'
[2024-12-02T08:18:18.075+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:18:18.090+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_cleanning.py took 0.406 seconds
[2024-12-02T08:18:48.362+0000] {processor.py:161} INFO - Started process (PID=327) to work on /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:18:48.362+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_cleanning.py for tasks to queue
[2024-12-02T08:18:48.365+0000] {logging_mixin.py:188} INFO - [2024-12-02T08:18:48.364+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:18:48.748+0000] {logging_mixin.py:188} INFO - [2024-12-02T08:18:48.744+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/data_cleanning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_cleanning.py", line 5, in <module>
    from data_cleaning import clean_data
ModuleNotFoundError: No module named 'data_cleaning'
[2024-12-02T08:18:48.749+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:18:48.763+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_cleanning.py took 0.404 seconds
[2024-12-02T08:19:19.232+0000] {processor.py:161} INFO - Started process (PID=342) to work on /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:19:19.233+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_cleanning.py for tasks to queue
[2024-12-02T08:19:19.236+0000] {logging_mixin.py:188} INFO - [2024-12-02T08:19:19.235+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:19:19.652+0000] {logging_mixin.py:188} INFO - [2024-12-02T08:19:19.648+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/data_cleanning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_cleanning.py", line 5, in <module>
    from data_cleaning import clean_data
ModuleNotFoundError: No module named 'data_cleaning'
[2024-12-02T08:19:19.653+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:19:19.668+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_cleanning.py took 0.440 seconds
[2024-12-02T08:19:49.820+0000] {processor.py:161} INFO - Started process (PID=359) to work on /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:19:49.821+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_cleanning.py for tasks to queue
[2024-12-02T08:19:49.823+0000] {logging_mixin.py:188} INFO - [2024-12-02T08:19:49.823+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:19:50.188+0000] {logging_mixin.py:188} INFO - [2024-12-02T08:19:50.185+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/data_cleanning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_cleanning.py", line 5, in <module>
    from data_cleaning import clean_data
ModuleNotFoundError: No module named 'data_cleaning'
[2024-12-02T08:19:50.189+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:19:50.202+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_cleanning.py took 0.386 seconds
[2024-12-02T08:20:20.489+0000] {processor.py:161} INFO - Started process (PID=374) to work on /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:20:20.490+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_cleanning.py for tasks to queue
[2024-12-02T08:20:20.493+0000] {logging_mixin.py:188} INFO - [2024-12-02T08:20:20.492+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:20:20.895+0000] {logging_mixin.py:188} INFO - [2024-12-02T08:20:20.892+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/data_cleanning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_cleanning.py", line 5, in <module>
    from data_cleaning import clean_data
ModuleNotFoundError: No module named 'data_cleaning'
[2024-12-02T08:20:20.896+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:20:20.910+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_cleanning.py took 0.425 seconds
[2024-12-02T08:20:51.428+0000] {processor.py:161} INFO - Started process (PID=389) to work on /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:20:51.429+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_cleanning.py for tasks to queue
[2024-12-02T08:20:51.433+0000] {logging_mixin.py:188} INFO - [2024-12-02T08:20:51.433+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:20:51.919+0000] {logging_mixin.py:188} INFO - [2024-12-02T08:20:51.917+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/data_cleanning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_cleanning.py", line 5, in <module>
ModuleNotFoundError: No module named 'data_cleaning'
[2024-12-02T08:20:51.920+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_cleanning.py
[2024-12-02T08:20:51.937+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_cleanning.py took 0.513 seconds
